  version: '3'
  services:
    restapi:
      build:
        #context: ./EffortlessApi
        context: ./
        dockerfile: Dockerfile
      expose:
        - 80
      restart: always
      environment:
        - VIRTUAL_HOST=netcore.fcoquiroz.com
        - LETSENCRYPT_HOST=netcore.fcoquiroz.com
        - LETSENCRYPT_EMAIL=fco.quiroz@outlook.com
  networks:
    default:
      external:
        name: nginx-proxy